R = $\begin{bmatrix} 2 & 4 & 1 & 0 \\ 3 & 0 & 1 & 4 \\ 0 & 2 & 4 & 3 \end{bmatrix}$

In [91]:
import numpy as np
R = np.array( [ [2, 4, 1, 0], [3, 0, 1, 4], [0, 2, 4, 3] ] )
print(R)

[[2 4 1 0]
 [3 0 1 4]
 [0 2 4 3]]


In [92]:
R[2,3]= -R[2,3]
print(R)

[[ 2  4  1  0]
 [ 3  0  1  4]
 [ 0  2  4 -3]]


In [132]:
B1 = B.transpose()

In [133]:
A*B1

matrix([[ 0, 16],
        [ 0, 31]])

In [134]:
import numpy as np
S = np.array([np.sqrt(1), np.sqrt(3), np.sqrt(5)])
print (S)

[1.         1.73205081 2.23606798]


In [137]:
B  = np.arange(-2,11,2)
print (B)

[-2  0  2  4  6  8 10]


In [138]:
B  = np.arange(-2,11,2)*3
print (B)

[-6  0  6 12 18 24 30]


In [140]:
F  = np.arange(45,4,-5)
print (F)

[45 40 35 30 25 20 15 10  5]


In [144]:
np.shape(F)

(9,)

In [145]:
help (np.pi)

Help on float object:

class float(object)
 |  float(x=0, /)
 |  
 |  Convert a string or number to a floating point number, if possible.
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __bool__(self, /)
 |      True if self else False
 |  
 |  __ceil__(self, /)
 |      Return the ceiling as an Integral.
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __float__(self, /)
 |      float(self)
 |  
 |  __floor__(self, /)
 |      Return the floor as an Integral.
 |  
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |  
 |  __format__(self, format_spec, /)
 |      Formats the float according to format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getnewargs__(self, /)
 |  
 |  __gt__(sel

In [154]:
x  = np.arange(0,15*np.pi/7,np.pi/6)
print (x)

[0.         0.52359878 1.04719755 1.57079633 2.0943951  2.61799388
 3.14159265 3.66519143 4.1887902  4.71238898 5.23598776 5.75958653
 6.28318531]


In [156]:
import numpy as np
C=np.cos(x)
print(C)


[ 1.00000000e+00  8.66025404e-01  5.00000000e-01  6.12323400e-17
 -5.00000000e-01 -8.66025404e-01 -1.00000000e+00 -8.66025404e-01
 -5.00000000e-01 -1.83697020e-16  5.00000000e-01  8.66025404e-01
  1.00000000e+00]


In [160]:
import numpy as np
S=np.sin(x)
print(S)

[ 0.00000000e+00  5.00000000e-01  8.66025404e-01  1.00000000e+00
  8.66025404e-01  5.00000000e-01  1.22464680e-16 -5.00000000e-01
 -8.66025404e-01 -1.00000000e+00 -8.66025404e-01 -5.00000000e-01
 -2.44929360e-16]


In [161]:
import numpy as np
T=np.tan(x)
print(T)

[ 0.00000000e+00  5.77350269e-01  1.73205081e+00  1.63312394e+16
 -1.73205081e+00 -5.77350269e-01 -1.22464680e-16  5.77350269e-01
  1.73205081e+00  5.44374645e+15 -1.73205081e+00 -5.77350269e-01
 -2.44929360e-16]


In [164]:
x2  = np.arange(-2,2.5,0.5)
print(x2)

[-2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2. ]


In [166]:
import numpy as np
y=np.cosh(x2)**2-np.sinh(x2)**2
print(y) 

[1. 1. 1. 1. 1. 1. 1. 1. 1.]
